version: '3.5'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
      - TZ=${TZ}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend
    restart: always

  redis:
    build:
      context: ./redis
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend
    restart: always

  mongo:
    build:
      context: ./mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/mongo:/data/db
      - ${DATA_PATH_HOST}/mongo_config:/data/configdb
    ports:
      - "${MONGO_PORT}:27017"
    networks:
      - backend
    restart: always

  mysql-manage:
    build:
      context: ./mysql-manage
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=${MYSQL_MANAGE_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_MANAGE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_MANAGE_ROOT_PASSWORD}
      - PMA_HOST=${MYSQL_MANAGE_CONNECT_HOST}
      - PMA_PORT=${MYSQL_MANAGE_CONNECT_PORT}
    ports:
      - "${MYSQL_MANAGE_PORT}:80"
    depends_on:
      - mysql
    networks:
      - backend
    restart: always

  redis-manage:
    build:
      context: ./redis-manage
    environment:
      - ADMIN_USER=${REDIS_MANAGE_USERNAME}
      - ADMIN_PASS=${REDIS_MANAGE_PASSWORD}
      - REDIS_1_HOST=${REDIS_MANAGE_CONNECT_HOST}
      - REDIS_1_PORT=${REDIS_MANAGE_CONNECT_PORT}
    ports:
      - "${REDIS_MANAGE_PORT}:80"
    depends_on:
      - redis
    networks:
      - backend
    restart: always

  mongo-manage:
    build:
      context: ./mongo-manage
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_MANAGE_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_MANAGE_PASSWORD}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_MANAGE_CONNECT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_MANAGE_CONNECT_PASSWORD}
      - ME_CONFIG_MONGODB_PORT=${MONGO_MANAGE_CONNECT_PORT}
      - ME_CONFIG_MONGODB_SERVER=${MONGO_MANAGE_CONNECT_HOST}
    ports:
      - "${MONGO_MANAGE_PORT}:8081"
    depends_on:
      - mongo
    networks:
      - backend
    restart: always

  nginx:
    build:
      context: ./nginx
    environment:
      - TZ=${TZ}
    volumes:
      - ${CODE_PATH_HOST}:/var/www
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${LOGS_PATH_HOST}/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
    networks:
      - backend
    restart: always

  php:
    build:
      context: ./php
      args:
        - TZ=${TZ}
        - PHP_CHANGE_SOURCE=${PHP_CHANGE_SOURCE}
        - PHP_INSTALL_PHALCON=${PHP_INSTALL_PHALCON}
    volumes:
      - ${PHP_CONFIG_PATH}/php7.3.ini:/usr/local/etc/php/php.ini
      - ${PHP_SUPERVISORD_PATH}:/etc/supervisord.d
      - ${CODE_PATH_HOST}:/var/www
      - ${LOGS_PATH_HOST}/supervisor:/var/log/supervisor
    expose:
      - "9000"
    networks:
      - backend
    restart: always
