version: '3.5'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}
volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}
  mongo:
    driver: ${VOLUMES_DRIVER}

services:
  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
      - TZ=${TZ}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend

  redis:
    build:
      context: ./redis
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend

  mongo:
    build:
      context: ./mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/mongo:/data/db
      - ${DATA_PATH_HOST}/mongo_config:/data/configdb
    ports:
      - "${MONGO_PORT}:27017"
    networks:
      - backend

  mysql-webui:
    build:
      context: ./mysql-webui
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=${MYSQL_WEBUI_USER}
      - MYSQL_PASSWORD=${MYSQL_WEBUI_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_WEBUI_ROOT_PASSWORD}
      - PMA_HOST=${MYSQL_WEBUI_CONNECT_HOST}
      - PMA_PORT=${MYSQL_WEBUI_CONNECT_PORT}
    ports:
      - "${MYSQL_WEBUI_PORT}:80"
    depends_on:
      - mysql
    networks:
      - frontend
      - backend

  redis-webui:
    build:
      context: ./redis-webui
    environment:
      - ADMIN_USER=${REDIS_WEBUI_USERNAME}
      - ADMIN_PASS=${REDIS_WEBUI_PASSWORD}
      - REDIS_1_HOST=${REDIS_WEBUI_CONNECT_HOST}
      - REDIS_1_PORT=${REDIS_WEBUI_CONNECT_PORT}
    ports:
      - "${REDIS_WEBUI_PORT}:80"
    depends_on:
      - redis
    networks:
      - frontend
      - backend

  mongo-webui:
    build:
      context: ./mongo-webui
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_WEBUI_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_WEBUI_PASSWORD}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_WEBUI_CONNECT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_WEBUI_CONNECT_PASSWORD}
      - ME_CONFIG_MONGODB_PORT=${MONGO_WEBUI_CONNECT_PORT}
      - ME_CONFIG_MONGODB_SERVER=${MONGO_WEBUI_CONNECT_HOST}
    ports:
      - "${MONGO_WEBUI_PORT}:8081"
    depends_on:
      - mongo
    networks:
      - frontend
      - backend

  nginx:
    build:
      context: ./nginx
    environment:
      - TZ=${TZ}
    volumes:
      - ${CODE_PATH_HOST}:/var/www
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${LOGS_PATH_HOST}/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
    networks:
      - frontend
      - backend

  php:
    build:
      context: ./php
      args:
        - PHP_INSTALL_PHALCON=${PHP_INSTALL_PHALCON}
        - TZ=${TZ}
    volumes:
      - ${PHP_CONFIG_PATH}/php7.3.ini:/usr/local/etc/php/php.ini
      - ${PHP_SUPERVISORD_PATH}:/etc/supervisord.d
      - ${CODE_PATH_HOST}:/var/www
      - ${LOGS_PATH_HOST}/supervisor:/var/log/supervisor
    expose:
      - "9000"
    networks:
      - backend
