name: github pages

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 代码检出
        uses: actions/checkout@v2

      - name: 构建部署
        uses: JamesIves/github-pages-deploy-action@4.1.8
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist
          BUILD_SCRIPT: npm install && npm run docs:build
