name: github pages

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 代码检出
        uses: actions/checkout@v2
        
      - name: 构建代码
        run: |
          npm install
          npm run docs:build

      - name: 部署代码
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          branch: gh-pages
          folder: docs/.vuepress/dist
